<?php
// no_son_tags.php
// Lista de etiquetas que deben ser eliminadas o ignoradas por el sistema.
// Actualizado con tercera lista del usuario (tags antiguos/renombrados).

return [
    // --- Lista 1 (Original) ---
    "escala en Asia",
    "error bajo los reflectores",
    "enfoque en prevención de carreras",
    "ElEmergente",
    "El Universal",
    "El Estímulo",
    "El Emergente",
    "Draft de Regla 5",
    "Dirigente",
    "Código de Ética",
    "cupo para lanzador importado",
    "Corpus Christi",
    "Corea del Sur",
    "control del caos",
    "Condiciones de Campeonato 2025-2026",
    "club de los 500 hits",
    "carácter competitivo",
    "bullpen",
    "Blanqueo 1-0",
    "Beisbol",
    "BCV",
    "bateo situacional",
    "bateo",
    "Barquisimeto",
    "Asia",
    "80 aniversario",
    "20-N",
    "filosofía de Ozzie Guillén",
    "fondo de la tabla",
    "futuro en beisbol organizado",
    "ganar juegos cerrados",
    "Grandes Ligas",
    "identidad del equipo sin Simmons",
    "impacto ofensivo melenuo",
    "IVC",
    "Japón",
    "jonrones",
    "Jonrones LVBP",
    "Juega En Línea",
    "juventud bajo examen",
    "Leones en crisis",
    "liderato en solitario",
    "Ligas Menores",
    "limpieza de roster",
    "Líder de Bateo",
    "líder jonronero del Caracas",
    "Magallanes se niega a morir",
    "margen de error mínimo",
    "medio juego de diferencia",
    "mejor staff de pitcheo",
    "mejor WHIP de la liga",
    "OPS sobre 1.000",
    "Novato del Año 2023–24",
    "no es corte definitivo",
    "movimiento planificado",
    "MVP de la Liga Mayor de Béisbol Profesional 2022",
    "menos carreras permitidas",
    "séptima semana",
    "staff candidato a enero",
    "Simmons fuera del roster",
    "shortstop titula",
    "seguro defensivo",
    "segunda oportunidad",
    "salió de Boston",
    "round robin en riesgo",
    "Round Robin",
    "Round Robi",
    "rotación de miedo",
    "Roster de 40",
    "reordenar campocorto",
    "relevo largo importado",
    "regreso en diciembre",
    "REEMPLAZAR_CON_ETIQUETA_3",
    "REEMPLAZAR_CON_ETIQUETA_2",
    "REEMPLAZAR_CON_ETIQUETA_1",
    "redención en la LVBP",
    "reconstrucción de carrera",
    "reacción turca",
    "Rally en el noveno",
    "rachas negativas",
    "rachas de remontada",
    "promedio sobre .330",
    "profundidad en la lomita",
    "presión del calendario",
    "presión de calendario",
    "pitcheo",
    "pieza clave del lineup",
    "pelea por el cuarto puesto",
    "“me duele la camisa”",
    "zona gris de la clasificación",
    "Wikipedia",
    "WhatsApp",
    "triple persecución",
    "Tiburones respiran",
    "Tiburones 2025-26",
    
    // --- Lista 2 (Agregada previamente) ---
    "Águilas líderes",
    "Antone refuerzo de lujo",
    "Clásico Mundial de Béisbol 2026",
    "Condiciones de Campeonato 2025-2026",
    "Estados Unidos",
    "impacto ofensivo melenudo",
    "Japón",
    "Maracaibo",
    "Margarita",
    "Ofensiva",
    "Quijada",
    "Quintana",
    "Semana de La Chinita",
    "shortstop titular",
    "Semana 6",
    "Caribe",

    // --- Lista 3 (Tags antiguos/renombrados a borrar) ---
    "500 hits en la LVBP",
    "Águilas",
    "Zulia",
    "Escobar",
    "Ali Castillo",
    "Bonaci",
    "Bravos",
    "Caribes",
    "Juego de la Chinita",
    "La Chinita",
    "Eliézer Alfonzo",
    "Alfonzo Jr.",
    "Eliezer Alfonso Jr.",
    "Alfonso \"Chico\" Carrasquel",
    "Alfonso “Chico” Carrasquel",
    "Barquisimeto",
    "Maracay",
    "Macuto",
    "Valencia",
    "Luis Aparicio",
    "Luis Aparicio \"El Grande\"",
    "Monumental",
    "Monumental de La Rinconada",
    "Monumental Simón Bolívar",
    "Guatamare.",
    "Nueva Esparta",
    "UCV",
    "Universitario",
    "Giovanny Carrara",
    "D’Orazio",
    "Jugador de la Semana 5",
    "Líder en deportes",
    "Sardiñas",
    "Suisbel",
    "LVBP.com",
    "Magallanes",
    "Daza"
];
